name: PyLint

on: [push, pull_request]

jobs:
  PEP8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.*

      - name: Install Python lint libraries
        run: |
          pip install autoflake isort black

      - name: Remove unused imports and variables
        run: |
          autoflake --in-place --recursive --remove-all-unused-imports --ignore-init-module-imports .

      - name: lint with isort
        run: |
          isort .

      - name: lint with black
        run: |
          black .

      # commit changes
      - name: Auto commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'ᴀᴜᴛᴏ ғɪxᴇs ʙʏ ᴋʀɪsʜɴᴀ' 
          commit_options: '--no-verify'
          repository: .
          commit_user_name: ˹ᴋʀɪsʜɴᴀ˼
          commit_user_email: OfficialKrishna7618@gmail.com
          commit_author: ˹ᴋʀɪsʜɴᴀ˼ <OfficialKrishna7618@gmail.com>
          
